### ISSUE TITLE
Problem with presentation api 3 manifests

### ISSUE THREAD

**Issue by liladude** [annonatate/annonatate#6]
Hi! I am unsure if the problem is in annonatate or in our manifests, so I am reporting. 
When loading a v.3 manifest of a book the thumbnails of pages are very slow at loading, cause an extreme load on our server and most of the time won't be visible at all. Also, annotations taken on images with v.3 manifest fail to load on the annotation list and are only visible as storyboard. When accessing the same images with a v. 2.1 I can see all the thumbnails immediately.
Here are is an example:

1. v2: https://dlib.biblhertz.it/iiif/be32153880/manifest2.json
2. v.3 https://dlib.biblhertz.it/iiif/be32153880/manifest.json
3. annotation https://annonatate.herokuapp.com/annotations/dlib2-biblhertz-it-3-be32153880-p0005-list.json
4. image view link https://ncsu-libraries.github.io/annona/tools/#/display?url=https://liladude.github.io/annonatate/annotations/dlib2-biblhertz-it-3-be32153880-p0005-list.json&viewtype=iiif-annotation
5. Storyboard: https://ncsu-libraries.github.io/annona/tools/#/display?url=https://liladude.github.io/annonatate/annotations/dlib2-biblhertz-it-3-be32153880-p0005-list.json&viewtype=iiif-storyboard&settings=%7B%22fullpage%22%3Atrue%7D

I am having hard time to find v.3 files in the web to compare, so let me know if our files are completely broken ;)
Best regards
Lila

**Comment by dnoneill** [comment]
The first issue is because when trying to load https://dlib2.biblhertz.it/iiif/3/be32153880@0149.jp2/full/max/0/default.jpg sometimes your server gets an error. It shouldn't be trying to load the full version anyway so I will look into this and fix it as well.

The second issue is because they changed the specs on v3 image servers. It used to be: https://dlib2.biblhertz.it/iiif/3/be32153880@0005.jp2/196,434,2228,1548/full/0/default.jpg, now it has to be https://dlib2.biblhertz.it/iiif/3/be32153880@0005.jp2/196,434,2228,1548/max/0/default.jpg. I will go ahead and integrate that into Annona.

I'll let you know when these changes are deployed. Thanks for reporting.

**Comment by liladude** [comment]
Thanks!

**Comment by dnoneill** [comment]
@liladude Issue one solved. Moving on to two.

**Comment by dnoneill** [comment]
@liladude Issue two should also be solved.

**Comment by liladude** [comment]
I can confirm! our images are now super fast at loading with v.3 and image view is working as well! Thank you!
